# mako template for Alembic migration scripts
"""
Revision ID: 2d89c4779e84
Revises: 20260213_rename_team_cols
Create Date: 2026-02-22 15:25:41.913326
"""
revision = "2d89c4779e84"
down_revision = '20260213_rename_team_cols'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraper_state')
    op.create_index('ix_alert_severity_ack', 'alerts', ['severity', 'acknowledged'], unique=False)
    op.create_index(op.f('ix_alerts_acknowledged'), 'alerts', ['acknowledged'], unique=False)
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.alter_column('bets', 'reason',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.create_index(op.f('ix_bets_bet_type'), 'bets', ['bet_type'], unique=False)
    op.create_index('ix_bets_parlay', 'bets', ['parlay_id'], unique=False, postgresql_where='parlay_id IS NOT NULL')
    op.create_index(op.f('ix_bets_placed_at'), 'bets', ['placed_at'], unique=False)
    op.create_index('ix_bets_placed_at_status', 'bets', ['placed_at', 'status'], unique=False)
    op.drop_constraint(op.f('fk_bets_player_id_players'), 'bets', type_='foreignkey')
    op.drop_constraint(op.f('fk_bets_game_id_games'), 'bets', type_='foreignkey')
    op.drop_constraint(op.f('fk_bets_sport_id_sports'), 'bets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bets_player_id_players'), 'bets', 'players', ['player_id'], ['player_id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_games_home_team_id_teams'), 'games', type_='foreignkey')
    op.drop_constraint(op.f('fk_games_away_team_id_teams'), 'games', type_='foreignkey')
    op.drop_constraint(op.f('fk_games_sport_id_sports'), 'games', type_='foreignkey')
    op.create_foreign_key(op.f('fk_games_away_team_id_teams'), 'games', 'teams', ['away_team_id'], ['team_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_games_sport_id_sports'), 'games', 'sports', ['sport_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_games_home_team_id_teams'), 'games', 'teams', ['home_team_id'], ['team_id'], ondelete='SET NULL')
    op.add_column('games_live', sa.Column('home_logo', sa.String(), nullable=True))
    op.add_column('games_live', sa.Column('away_logo', sa.String(), nullable=True))
    op.drop_constraint(op.f('fk_games_live_game_id_games'), 'games_live', type_='foreignkey')
    op.create_foreign_key(op.f('fk_games_live_game_id_games'), 'games_live', 'games', ['game_id'], ['game_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_games_results_away_team_id'), 'games_results', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_games_results_game_id'), 'games_results', ['game_id'], unique=False)
    op.create_index(op.f('ix_games_results_home_team_id'), 'games_results', ['home_team_id'], unique=False)
    op.drop_constraint(op.f('fk_games_results_game_id_games'), 'games_results', type_='foreignkey')
    op.drop_constraint(op.f('fk_games_results_home_team_id_teams'), 'games_results', type_='foreignkey')
    op.drop_constraint(op.f('fk_games_results_away_team_id_teams'), 'games_results', type_='foreignkey')
    op.create_foreign_key(op.f('fk_games_results_home_team_id_teams'), 'games_results', 'teams', ['home_team_id'], ['team_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_games_results_away_team_id_teams'), 'games_results', 'teams', ['away_team_id'], ['team_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_games_results_game_id_games'), 'games_results', 'games', ['game_id'], ['game_id'], ondelete='CASCADE')
    op.drop_column('games_results', 'moved_at_new')
    op.create_index(op.f('ix_games_upcoming_away_team_id'), 'games_upcoming', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_games_upcoming_game_id'), 'games_upcoming', ['game_id'], unique=False)
    op.create_index(op.f('ix_games_upcoming_home_team_id'), 'games_upcoming', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_games_upcoming_scraped_at'), 'games_upcoming', ['scraped_at'], unique=False)
    op.drop_constraint(op.f('fk_games_upcoming_away_team_id_teams'), 'games_upcoming', type_='foreignkey')
    op.drop_constraint(op.f('fk_games_upcoming_home_team_id_teams'), 'games_upcoming', type_='foreignkey')
    op.drop_constraint(op.f('fk_games_upcoming_game_id_games'), 'games_upcoming', type_='foreignkey')
    op.create_foreign_key(op.f('fk_games_upcoming_game_id_games'), 'games_upcoming', 'games', ['game_id'], ['game_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_games_upcoming_away_team_id_teams'), 'games_upcoming', 'teams', ['away_team_id'], ['team_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_games_upcoming_home_team_id_teams'), 'games_upcoming', 'teams', ['home_team_id'], ['team_id'], ondelete='SET NULL')
    op.alter_column('injuries', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('injuries', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('fk_injuries_team_id_teams'), 'injuries', type_='foreignkey')
    op.drop_constraint(op.f('fk_injuries_player_id_players'), 'injuries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_injuries_team_id_teams'), 'injuries', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_injuries_player_id_players'), 'injuries', 'players', ['player_id'], ['player_id'], ondelete='CASCADE')
    op.alter_column('player_stats', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('uq_player_stats_game_player'), table_name='player_stats')
    op.create_unique_constraint('uq_player_stats_game_player', 'player_stats', ['game_id', 'player_id'])
    op.create_index('ix_player_stats_game_sport', 'player_stats', ['game_id', 'sport'], unique=False)
    op.create_index('ix_player_stats_player_scraped', 'player_stats', ['player_id', 'scraped_at'], unique=False)
    op.drop_constraint(op.f('fk_player_stats_game_id_games_results'), 'player_stats', type_='foreignkey')
    op.drop_constraint(op.f('fk_player_stats_team_id_teams'), 'player_stats', type_='foreignkey')
    op.drop_constraint(op.f('fk_player_stats_player_id_players'), 'player_stats', type_='foreignkey')
    op.create_foreign_key(op.f('fk_player_stats_player_id_players'), 'player_stats', 'players', ['player_id'], ['player_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_player_stats_team_id_teams'), 'player_stats', 'teams', ['team_id'], ['team_id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_players_team_id_teams'), 'players', type_='foreignkey')
    op.create_foreign_key(op.f('fk_players_team_id_teams'), 'players', 'teams', ['team_id'], ['team_id'], ondelete='SET NULL')
    op.drop_constraint(op.f('unique_sport_name'), 'sports', type_='unique')
    op.alter_column('standings', 'season_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_standing_season_rank', 'standings', ['season_year', 'rank'], unique=False)
    op.drop_constraint(op.f('fk_standings_team_id_teams'), 'standings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_standings_team_id_teams'), 'standings', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_teams_sport_id_sports'), 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('fk_teams_sport_id_sports'), 'teams', 'sports', ['sport_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_teams_sport_id_sports'), 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('fk_teams_sport_id_sports'), 'teams', 'sports', ['sport_id'], ['id'])
    op.drop_constraint(op.f('fk_standings_team_id_teams'), 'standings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_standings_team_id_teams'), 'standings', 'teams', ['team_id'], ['team_id'])
    op.drop_index('ix_standing_season_rank', table_name='standings')
    op.alter_column('standings', 'season_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(op.f('unique_sport_name'), 'sports', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('fk_players_team_id_teams'), 'players', type_='foreignkey')
    op.create_foreign_key(op.f('fk_players_team_id_teams'), 'players', 'teams', ['team_id'], ['team_id'])
    op.drop_constraint(op.f('fk_player_stats_team_id_teams'), 'player_stats', type_='foreignkey')
    op.drop_constraint(op.f('fk_player_stats_player_id_players'), 'player_stats', type_='foreignkey')
    op.create_foreign_key(op.f('fk_player_stats_player_id_players'), 'player_stats', 'players', ['player_id'], ['player_id'])
    op.create_foreign_key(op.f('fk_player_stats_team_id_teams'), 'player_stats', 'teams', ['team_id'], ['team_id'])
    op.create_foreign_key(op.f('fk_player_stats_game_id_games_results'), 'player_stats', 'games_results', ['game_id'], ['game_id'])
    op.drop_index('ix_player_stats_player_scraped', table_name='player_stats')
    op.drop_index('ix_player_stats_game_sport', table_name='player_stats')
    op.drop_constraint('uq_player_stats_game_player', 'player_stats', type_='unique')
    op.create_index(op.f('uq_player_stats_game_player'), 'player_stats', ['game_id', 'player_id'], unique=True)
    op.alter_column('player_stats', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('fk_injuries_player_id_players'), 'injuries', type_='foreignkey')
    op.drop_constraint(op.f('fk_injuries_team_id_teams'), 'injuries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_injuries_player_id_players'), 'injuries', 'players', ['player_id'], ['player_id'])
    op.create_foreign_key(op.f('fk_injuries_team_id_teams'), 'injuries', 'teams', ['team_id'], ['team_id'])
    op.alter_column('injuries', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('injuries', 'description',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_games_upcoming_home_team_id_teams'), 'games_upcoming', type_='foreignkey')
    op.drop_constraint(op.f('fk_games_upcoming_away_team_id_teams'), 'games_upcoming', type_='foreignkey')
    op.drop_constraint(op.f('fk_games_upcoming_game_id_games'), 'games_upcoming', type_='foreignkey')
    op.create_foreign_key(op.f('fk_games_upcoming_game_id_games'), 'games_upcoming', 'games', ['game_id'], ['game_id'])
    op.create_foreign_key(op.f('fk_games_upcoming_home_team_id_teams'), 'games_upcoming', 'teams', ['home_team_id'], ['team_id'])
    op.create_foreign_key(op.f('fk_games_upcoming_away_team_id_teams'), 'games_upcoming', 'teams', ['away_team_id'], ['team_id'])
    op.drop_index(op.f('ix_games_upcoming_scraped_at'), table_name='games_upcoming')
    op.drop_index(op.f('ix_games_upcoming_home_team_id'), table_name='games_upcoming')
    op.drop_index(op.f('ix_games_upcoming_game_id'), table_name='games_upcoming')
    op.drop_index(op.f('ix_games_upcoming_away_team_id'), table_name='games_upcoming')
    op.add_column('games_results', sa.Column('moved_at_new', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_games_results_game_id_games'), 'games_results', type_='foreignkey')
    op.drop_constraint(op.f('fk_games_results_away_team_id_teams'), 'games_results', type_='foreignkey')
    op.drop_constraint(op.f('fk_games_results_home_team_id_teams'), 'games_results', type_='foreignkey')
    op.create_foreign_key(op.f('fk_games_results_away_team_id_teams'), 'games_results', 'teams', ['away_team_id'], ['team_id'])
    op.create_foreign_key(op.f('fk_games_results_home_team_id_teams'), 'games_results', 'teams', ['home_team_id'], ['team_id'])
    op.create_foreign_key(op.f('fk_games_results_game_id_games'), 'games_results', 'games', ['game_id'], ['game_id'])
    op.drop_index(op.f('ix_games_results_home_team_id'), table_name='games_results')
    op.drop_index(op.f('ix_games_results_game_id'), table_name='games_results')
    op.drop_index(op.f('ix_games_results_away_team_id'), table_name='games_results')
    op.drop_constraint(op.f('fk_games_live_game_id_games'), 'games_live', type_='foreignkey')
    op.create_foreign_key(op.f('fk_games_live_game_id_games'), 'games_live', 'games', ['game_id'], ['game_id'])
    op.drop_column('games_live', 'away_logo')
    op.drop_column('games_live', 'home_logo')
    op.drop_constraint(op.f('fk_games_home_team_id_teams'), 'games', type_='foreignkey')
    op.drop_constraint(op.f('fk_games_sport_id_sports'), 'games', type_='foreignkey')
    op.drop_constraint(op.f('fk_games_away_team_id_teams'), 'games', type_='foreignkey')
    op.create_foreign_key(op.f('fk_games_sport_id_sports'), 'games', 'sports', ['sport_id'], ['id'])
    op.create_foreign_key(op.f('fk_games_away_team_id_teams'), 'games', 'teams', ['away_team_id'], ['team_id'])
    op.create_foreign_key(op.f('fk_games_home_team_id_teams'), 'games', 'teams', ['home_team_id'], ['team_id'])
    op.drop_constraint(op.f('fk_bets_player_id_players'), 'bets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bets_sport_id_sports'), 'bets', 'sports', ['sport_id'], ['id'])
    op.create_foreign_key(op.f('fk_bets_game_id_games'), 'bets', 'games', ['game_id'], ['game_id'])
    op.create_foreign_key(op.f('fk_bets_player_id_players'), 'bets', 'players', ['player_id'], ['player_id'])
    op.drop_index('ix_bets_placed_at_status', table_name='bets')
    op.drop_index(op.f('ix_bets_placed_at'), table_name='bets')
    op.drop_index('ix_bets_parlay', table_name='bets', postgresql_where='parlay_id IS NOT NULL')
    op.drop_index(op.f('ix_bets_bet_type'), table_name='bets')
    op.alter_column('bets', 'reason',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_acknowledged'), table_name='alerts')
    op.drop_index('ix_alert_severity_ack', table_name='alerts')
    op.create_table('scraper_state',
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('scraper_state_pkey'))
    )
    # ### end Alembic commands ###
